name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: composer install

      - name: Lint
        run: composer lint

      - name: Unit Test
        run: composer test

      - name: Acceptance Test
        run: ./vendor/bin/phpunit tests/Acceptance
        env:
          CODING_PERSONAL_TOKEN: ${{ secrets.CODING_PERSONAL_TOKEN }}
          CODING_PASSWORD: ${{ secrets.CODING_PASSWORD }}
          CODING_USERNAME: ${{ secrets.CODING_USERNAME }}
          CODING_TEAM_DOMAIN: ${{ secrets.CODING_TEAM_DOMAIN }}
          CODING_PROJECT_TOKEN: ${{ secrets.CODING_PROJECT_TOKEN }}
          CODING_PROJECT_NAME: ${{ secrets.CODING_PROJECT_NAME }}
          CODING_DEPOT_ID: ${{ secrets.CODING_DEPOT_ID }}

      - name: codecov
        uses: codecov/codecov-action@v2
